language: node_js
node_js:
- node
script:
- webpack
deploy:
  matrix:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    local_dir: dist
    on:
      branch: master
  - provider: npm
    email: "$EMAIL"
    skip_cleanup: true
    api_key: "$NPM_TOKEN"
    on:
      tags: true
env:
  matrix:
  - secure: qLOlAaqwFE7HjLuqQSKDtvalPjyhYQWvdxkVLee9y6SNp5QWTQ42uej1xcVqH8E1DYThXB2d0Coa4gDFowWIdHOD0If2iNiqievb9rm6XQNsPlygJu34bUqPTj0gpriUMC7e3boVav1QszHvrjc4QoL5D+76Sqz6ukXnwQvyE03Mg61qO3HpdsQ0rJ7JtnIakPacNCp0UaMM+XPWjOPZmW0YR0JxE9Dmxkqwe/38D5Nn5dtzbyWGfc7C6ooYZLlhsmh1sF1nED+k+DLUkHGKK6bvfeSfsXZ7s0iNF9KP/RlLOz2QPusrYU6rXXhn5afYkN0KZu21w0kO0lvpxOdfzECjyWenKnLaY7Ued5sFFEUiYXgr8mVxX9nFF8wAQ/ujDbHlIF8JzQAlOm2T7F9i7H/EFrnBlJ/aPk3qc8/wnfMs8C+q3ERum48jqqIBL/K1pgtU+4oyAXGl01ZYfKg960PG/rRtOyhULiV20CWIlmF8I/roa2zhB0gRnSF8UsqYgX6bxKCRfS9YNFRZvc/BL+6ijXrzavHhN+d08506V7AkDONfTxn+wmdxClbc78GCwNMRqKKSRf8jc/Ung7oiZ6zikQDQadBKhhaHOU9jDVTddDbBh79zcHRu/v8pqjtvIbraO6Kid6appAzWkdroAGOhDPJOyuKS0HZnmRJnbzw=
  - secure: f8OkIBi6bchdYMmo2oAzEswn3biWzWBux8OexYEHHM2eGTR0qCfaBu3sAHalQs1onLAOnPbNL8Y13Oh9ZtX3kMIFcK0Uhh/SEvzAYRPCnsmNHAQxCqVrL07BKwmcdCVdDz9zvBbUrptzWqug1vSxGzIGSK6qRxRxS6OYPHIR5bGUHjfFIKkmhqz+KsZMRoY9FqxBe6TQvPWtxc2rJMVxAHwPqYfXrxlM3BBQjgf6jOGh2BwsumgLcn7DXC7klPaNI2OOLYDRlrO7taCjVsDylsWJHBlhDlpMwWTqWmZtv4r2hFWbl1smNub044h131PFp0ALua0cF/QIZfEZngJNYFSr5lIOyvLwetMQ/SK8cTrhhdMK9Z98tE88DOt27KcsDg4McwrG9/eTiik7Cz5bv7hWimuprHTWNcFoxd0IDvkynJHdgTjR2qEDQbcRt9mOc24VfkjKq5KFkvbC1dqsLEDwcUPau/E0cHXxGiASH7eFLZRRnzArF46QPflH8qyp/BFN1sZmsCo4VdmAECxNsLNbL3DlQx+RyoruLaphx2cXw7pSxXIIl2sloID4X/EqM979Ex3Ropatqm6GpQMamQtjjw+F55HERzRJBcn8JMF06J8tOEKgvMjBvMX1tOHguMxb8KHdiQcEha4qxJ15Vi2WMoANHy9TxDmeqbO3hRw=
